JOB_CODE_TRAIN_YOLO = "JobTrainYolo"
JOB_CODE_BUILD_MODEL_HIERARCHY = "JobBuildModelHierarchy"
JOB_CODE_EVALUATE_MODEL = "JobEvaluateModel"

JOB_CODE_UPLOAD_CONFIGURATION_DATA = "JobUploadConfigurationData"


RETRYABLE_JOBS = [JOB_CODE_TRAIN_YOLO]
